In [ ]:
import numpy
numpy.__version__

'2.5.3'

In [ ]:
import numpy as np

threeD = np.array([[[1,3,4] , [4,5,6]] , [[2,3,4] , [5,3,2]] , [[2,5,8] , [4,67,9]]])
print(threeD)
print(threeD.shape)
print(threeD)



[[[ 1  3  4]
  [ 4  5  6]]

 [[ 2  3  4]
  [ 5  3  2]]

 [[ 2  5  8]
  [ 4 67  9]]]
(3, 2, 3)


In [10]:
import numpy as np

x = np.zeros((3,4) ,dtype = float)
x


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr = np.arange(0,12,2)
print(arr)
print(type(arr))

[ 0  2  4  6  8 10]
<class 'numpy.ndarray'>


In [ ]:
arr = np.linspace(0,10,8)
print(arr)


[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]


In [13]:
import numpy as np
import sys

List1 = [1,2,3,4,5,6,7]
print(sys.getsizeof(List1))

arr = np.array(List1)
print(arr.size*arr.itemsize)
print(arr.nbytes)

120
56
56


In [14]:
import numpy as np
import time

l1 = range(1 , 10000)
l2 = range(1,10000)

A1 = np.array(l1)
A2 = np.array(l2)

start = time.time()
result1 = [x+y for x,y in zip(l1 , l2)]
print((time.time() - start) * 10000)

start1 = time.time()
result2 = A1+A2

print((time.time() - start1)*10000)

10.986328125
20.813941955566406
