In [10]:
import numpy
numpy.__version__

'2.5.3'

In [11]:
import numpy as np

threeD = np.array([[[1,3,4] , [4,5,6]] , [[2,3,4] , [5,3,2]] , [[2,5,8] , [4,67,9]]])
print(threeD)
print(threeD.shape)
print(threeD)



[[[ 1  3  4]
  [ 4  5  6]]

 [[ 2  3  4]
  [ 5  3  2]]

 [[ 2  5  8]
  [ 4 67  9]]]
(3, 2, 3)
[[[ 1  3  4]
  [ 4  5  6]]

 [[ 2  3  4]
  [ 5  3  2]]

 [[ 2  5  8]
  [ 4 67  9]]]


In [12]:
import numpy as np

x = np.zeros((3,4) ,dtype = float)
x


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
arr = np.arange(0,12,2)
print(arr)
print(type(arr))

[ 0  2  4  6  8 10]
<class 'numpy.ndarray'>


In [14]:
arr = np.linspace(0,10,8)
print(arr)


[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]


In [15]:
import numpy as np
import sys

List1 = [1,2,3,4,5,6,7]
print(sys.getsizeof(List1))

arr = np.array(List1)
print(arr.size*arr.itemsize)
print(arr.nbytes)

120
56
56


In [16]:
import numpy as np
import time

l1 = range(1 , 10000)
l2 = range(1,10000)

A1 = np.array(l1)
A2 = np.array(l2)

start = time.time()
result1 = [x+y for x,y in zip(l1 , l2)]
print((time.time() - start) * 10000)

start1 = time.time()
result2 = A1+A2

print((time.time() - start1)*10000)

11.19852066040039
8.134841918945312


In [17]:
#Broadcasting

a = np.array([1,2,3])
b = 5

print(a*b)


arr = np.array([[1,2,3]])
vec = np.array([[1] , [2] , [3]])

print(arr + vec)

[ 5 10 15]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [18]:
import numpy as np

x = np.random.randint(5,10,size = 10)

print(x)

y = np.random.seed(101);
y = np.random.randint(5,10,size = (3,2))

print(y)

[7 7 6 9 5 5 5 5 5 7]
[[8 6]
 [8 6]
 [5 9]]


In [19]:
import numpy as np

x = np.random.randint(5,10 , size = (3,4))


print(x)

[[5 9 9 5]
 [9 5 6 8]
 [7 5 8 8]]


In [20]:
lst = [1,2,3,4,5,6,7,8,9]

print(lst[1:4])
print(lst[ :1])
print(lst[4: ])
print(lst[ 1:2])

[2, 3, 4]
[1]
[5, 6, 7, 8, 9]
[2]


In [33]:
import numpy as np

x = np.array([1,4,6,8,10,12])

print(x[1:])

print(x[-1:])

print(x[1:4])

print(x[ : 3])

print(x[ :-1])

print(x[ : -4])

print(x[ :: -1]) # Reverse the array.


[ 4  6  8 10 12]
[12]
[4 6 8]
[1 4 6]
[ 1  4  6  8 10]
[1 4]
[12 10  8  6  4  1]


In [ ]:
import numpy as np

x = np.array([
	[1, 2, 3, 4],
	[4, 5, 6, 7],
	[8, 9, 10, 11],
	[12, 13, 14, 15]
])

print(x[1:2, :]) #[ : start row , : end row : start coloumn , : end coloumn.]

print(x[:3, :])

print(x[:3 , 1 : 3])

print(x[:,:-1])

[[4 5 6 7]]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  3]
 [ 5  6]
 [ 9 10]]
[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
